name: Deploy React App to AWS

on:
  workflow_dispatch: # Manual trigger for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Extract Commit Hash
    - name: Extract Commit Hash
      id: commit
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "Commit hash: $COMMIT_HASH"
        echo "::set-output name=commit_hash::$COMMIT_HASH"

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    # Step 4: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}

    # Step 5: Build and Push Docker Image to ECR
    - name: Build and push Docker image
      run: |
        # Build and tag the Docker image
        IMAGE_TAG=${{ steps.commit.outputs.commit_hash }}
        ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/bjj-tracker-react

        echo "VITE_REACT_APP_API_BASE_URL=${VITE_REACT_APP_API_BASE_URL}" > .env.production

        echo "Docker Image: bjj-tracker-react:$IMAGE_TAG"

        docker build -t bjj-tracker-react:$IMAGE_TAG .
        docker tag bjj-tracker-react:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:$IMAGE_TAG
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        VITE_REACT_APP_API_BASE_URL: ${{ secrets.VITE_REACT_APP_API_BASE_URL }}

    # Step 6: Replace Placeholders in Task Definition
    - name: Replace Placeholders in Task Definition
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        VERSION: ${{ steps.commit.outputs.commit_hash }}
      run: |
        envsubst < aws/react-task-template.json > aws/react-task.json
        echo "Version: $VERSION"

    # Step 5: Update ECS Service
    - name: Update ECS Service
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws ecs update-service \
          --cluster bjj-tracker-cluster \
          --service bjj-tracker-react-service \
          --task-definition react-task \
          --force-new-deployment